souffle: souffle::RamRelation Class Reference
souffle::RamRelation Class Reference
A RAM Relation in the RAM intermediate representation.
#include <RamRelation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamRelation * clone () const override
Create clone.
const std::string getArg (uint32_t i) const
Get argument.
const std::string getArgTypeQualifier (uint32_t i) const
unsigned getArity () const
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const std::string & getName () const
Get name.
const SymbolMask & getSymbolMask () const
Get symbol mask.
const bool isBrie () const
Is Brie relation.
const bool isBTree () const
Is BTree relation.
const bool isComputed () const
Is relation computed.
const bool isCoverable () const
const bool isEqRel () const
Is equivalence relation.
const bool isInput () const
Is input relation.
const bool isOutput () const
Is output relation.
const bool isTemp () const
Is temporary relation (for semi-naive evaluation)
bool operator< (const RamRelation &other) const
void print (std::ostream &out) const override
Print RAM node.
RamRelation (const std::string name, const size_t arity, const std::vector< std::string > attributeNames, const std::vector< std::string > attributeTypeQualifiers, const SymbolMask mask, const bool input, const bool computed, const bool output, const bool btree, const bool brie, const bool eqrel)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
const size_t arity
Arity, i.e., number of attributes.
const std::vector< std::string > attributeNames
Name of attributes.
const std::vector< std::string > attributeTypeQualifiers
Type of attributes.
const bool brie
const bool btree
const bool computed
const bool eqrel
const bool input
Relation qualifiers.
const SymbolMask mask
TODO (#541): legacy, i.e., duplicated information.
const std::string name
Name of relation.
const bool output
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 38 of file RamRelation.h.
Constructor & Destructor Documentation
souffle::RamRelation::RamRelation (const std::string name, const size_t arity, const std::vector< std::string > attributeNames, const std::vector< std::string > attributeTypeQualifiers, const SymbolMask mask, const bool input, const bool computed, const bool output, const bool btree, const bool brie, const bool eqrel) inline
Definition at line 66 of file RamRelation.h.
Referenced by clone().
             : RamNode(RN_Relation), name(std::move(name)), arity(arity),
               attributeNames(std::move(attributeNames)),
               attributeTypeQualifiers(std::move(attributeTypeQualifiers)), mask(std::move(mask)),
               input(input), output(output), computed(computed), btree(btree), brie(brie), eqrel(eqrel) {
         assert(this->attributeNames.size() == arity || this->attributeNames.empty());
         assert(this->attributeTypeQualifiers.size() == arity || this->attributeTypeQualifiers.empty());
     }
Member Function Documentation
void souffle::RamRelation::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 180 of file RamRelation.h.
 {}
RamRelation* souffle::RamRelation::clone () const inline override virtual
Create clone.
Implements souffle::RamNode.
Definition at line 173 of file RamRelation.h.
References arity, attributeNames, attributeTypeQualifiers, brie, btree, computed, eqrel, input, mask, name, output, and RamRelation().
{
         RamRelation* res = new RamRelation(name, arity, attributeNames, attributeTypeQualifiers, mask, input,
                 computed, output, btree, brie, eqrel);
         return res;
     }
bool souffle::RamRelation::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 184 of file RamRelation.h.
References arity, attributeNames, attributeTypeQualifiers, isBrie(), isBTree(), isComputed(), isEqRel(), isInput(), isOutput(), isTemp(), souffle::SymbolMask::mask, mask, and name.
{
         assert(nullptr != dynamic_cast<const RamRelation*>(&node));
         const auto& other = static_cast<const RamRelation&>(node);
         return name == other.name && arity == other.arity && attributeNames == other.attributeNames &&
                attributeTypeQualifiers == other.attributeTypeQualifiers && mask == other.mask &&
                isInput() == other.isInput() && isOutput() == other.isOutput() &&
                isComputed() == other.isComputed() && isBTree() == other.isBTree() &&
                isBrie() == other.isBrie() && isEqRel() == other.isEqRel() && isTemp() == other.isTemp();
     }
const std::string souffle::RamRelation::getArg (uint32_t i) const inline
Get argument.
Definition at line 83 of file RamRelation.h.
References arity, attributeNames, and i.
Referenced by souffle::RamRelationReference::getArg(), souffle::InterpreterProgInterface::InterpreterProgInterface(), and print().
{
         if (!attributeNames.empty()) {
             return attributeNames[i];
         }
         if (arity == 0) {
             return "";
         }
         return "c" + std::to_string(i);
     }
const std::string souffle::RamRelation::getArgTypeQualifier (uint32_t i) const inline
Definition at line 93 of file RamRelation.h.
References attributeTypeQualifiers.
Referenced by souffle::RamRelationReference::getArgTypeQualifier(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return (i < attributeTypeQualifiers.size()) ? attributeTypeQualifiers[i] : "";
     }
unsigned souffle::RamRelation::getArity () const inline
Definition at line 143 of file RamRelation.h.
References arity.
Referenced by souffle::RamRelationReference::getArity(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return arity;
     }
std::vector<const RamNode*> souffle::RamRelation::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 168 of file RamRelation.h.
{
         return std::vector<const RamNode*>();  // no child nodes
     }
const std::string& souffle::RamRelation::getName () const inline
Get name.
Definition at line 78 of file RamRelation.h.
References name.
Referenced by souffle::RamRelationReference::getName(), and souffle::InterpreterProgInterface::InterpreterProgInterface().
{
         return name;
     }
const SymbolMask& souffle::RamRelation::getSymbolMask () const inline
Get symbol mask.
Definition at line 98 of file RamRelation.h.
References mask.
Referenced by souffle::RamRelationReference::getSymbolMask().
{
         return mask;
     }
const bool souffle::RamRelation::isBrie () const inline
Is Brie relation.
Definition at line 123 of file RamRelation.h.
References brie.
Referenced by equal(), souffle::RamRelationReference::isBrie(), and print().
{
         return brie;
     }
const bool souffle::RamRelation::isBTree () const inline
Is BTree relation.
Definition at line 118 of file RamRelation.h.
References btree.
Referenced by equal(), souffle::RamRelationReference::isBTree(), and print().
{
         return btree;
     }
const bool souffle::RamRelation::isComputed () const inline
Is relation computed.
Definition at line 108 of file RamRelation.h.
References computed.
Referenced by equal(), and souffle::RamRelationReference::isComputed().
{
         return computed;
     }
const bool souffle::RamRelation::isCoverable () const inline
Definition at line 133 of file RamRelation.h.
{
         return true;
     }
const bool souffle::RamRelation::isEqRel () const inline
Is equivalence relation.
Definition at line 128 of file RamRelation.h.
References eqrel.
Referenced by equal(), souffle::RamRelationReference::isEqRel(), and print().
{
         return eqrel;
     }
const bool souffle::RamRelation::isInput () const inline
Is input relation.
Definition at line 103 of file RamRelation.h.
References input.
Referenced by equal(), and souffle::RamRelationReference::isInput().
{
         return input;
     }
const bool souffle::RamRelation::isOutput () const inline
Is output relation.
Definition at line 113 of file RamRelation.h.
References output.
Referenced by equal(), and souffle::RamRelationReference::isOutput().
{
         return output;
     }
const bool souffle::RamRelation::isTemp () const inline
Is temporary relation (for semi-naive evaluation)
Definition at line 138 of file RamRelation.h.
References name.
Referenced by equal(), and souffle::RamRelationReference::isTemp().
{
         return name.at(0) == '@';
     }
bool souffle::RamRelation::operator< (const RamRelation & other) const inline
Definition at line 148 of file RamRelation.h.
References name.
{
         return name < other.name;
     }
void souffle::RamRelation::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 153 of file RamRelation.h.
References arity, getArg(), i, isBrie(), isBTree(), isEqRel(), and name.
{
         out << name << "(";
         out << getArg(0);
         for (unsigned i = 1; i < arity; i++) {
             out << ",";
             out << getArg(i);
         }
         out << ")";
         if (isBTree()) out << " btree";
         if (isBrie()) out << " brie";
         if (isEqRel()) out << " eqrel";
     }
Field Documentation
const size_t souffle::RamRelation::arity protected
Arity, i.e., number of attributes.
Definition at line 44 of file RamRelation.h.
Referenced by clone(), equal(), getArg(), getArity(), and print().
const std::vector<std::string> souffle::RamRelation::attributeNames protected
Name of attributes.
Definition at line 47 of file RamRelation.h.
Referenced by clone(), equal(), and getArg().
const std::vector<std::string> souffle::RamRelation::attributeTypeQualifiers protected
Type of attributes.
Definition at line 50 of file RamRelation.h.
Referenced by clone(), equal(), and getArgTypeQualifier().
const bool souffle::RamRelation::brie protected
Definition at line 62 of file RamRelation.h.
Referenced by clone(), and isBrie().
const bool souffle::RamRelation::btree protected
Definition at line 61 of file RamRelation.h.
Referenced by clone(), and isBTree().
const bool souffle::RamRelation::computed protected
Definition at line 59 of file RamRelation.h.
Referenced by clone(), and isComputed().
const bool souffle::RamRelation::eqrel protected
Definition at line 63 of file RamRelation.h.
Referenced by clone(), and isEqRel().
const bool souffle::RamRelation::input protected
Relation qualifiers.
Definition at line 57 of file RamRelation.h.
Referenced by clone(), and isInput().
const SymbolMask souffle::RamRelation::mask protected
TODO (#541): legacy, i.e., duplicated information.
Definition at line 53 of file RamRelation.h.
Referenced by clone(), equal(), and getSymbolMask().
const std::string souffle::RamRelation::name protected
Name of relation.
Definition at line 41 of file RamRelation.h.
Referenced by clone(), equal(), getName(), isTemp(), operator<(), and print().
const bool souffle::RamRelation::output protected
Definition at line 58 of file RamRelation.h.
Referenced by clone(), and isOutput().
The documentation for this class was generated from the following file:
RamRelation.h