souffle: souffle::RamEmpty Class Reference
souffle::RamEmpty Class Reference
Emptiness check for a relation.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply.
RamEmpty * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
size_t getLevel () override
Get level.
const RamRelationReference & getRelation () const
Get relation.
void print (std::ostream &os) const override
Print.
RamEmpty (std::unique_ptr< RamRelationReference > rel)
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Private Attributes
std::unique_ptr
< RamRelationReference > relation
Relation.
Detailed Description
Emptiness check for a relation.
Definition at line 445 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamEmpty::RamEmpty (std::unique_ptr< RamRelationReference > rel) inline
Definition at line 450 of file RamCondition.h.
Referenced by clone().
 : RamCondition(RN_Empty), relation(std::move(rel)) {}
Member Function Documentation
void souffle::RamEmpty::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 479 of file RamCondition.h.
References map, and relation.
{
         relation = map(std::move(relation));
     }
RamEmpty* souffle::RamEmpty::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 473 of file RamCondition.h.
References RamEmpty(), and relation.
{
         RamEmpty* res = new RamEmpty(std::unique_ptr<RamRelationReference>(relation->clone()));
         return res;
     }
bool souffle::RamEmpty::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 485 of file RamCondition.h.
References souffle::RamRelationReference::getRelation(), and getRelation().
{
         assert(nullptr != dynamic_cast<const RamEmpty*>(&node));
         const auto& other = static_cast<const RamEmpty&>(node);
         return getRelation() == other.getRelation();
     }
std::vector<const RamNode*> souffle::RamEmpty::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 468 of file RamCondition.h.
References relation.
{
         return std::vector<const RamNode*>() = {relation.get()};
     }
size_t souffle::RamEmpty::getLevel () inline override virtual
Get level.
Implements souffle::RamCondition.
Definition at line 458 of file RamCondition.h.
{
         return 0;  // can be in the top level
     }
const RamRelationReference& souffle::RamEmpty::getRelation () const inline
Get relation.
Definition at line 453 of file RamCondition.h.
References relation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         return *relation;
     }
void souffle::RamEmpty::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 463 of file RamCondition.h.
References relation.
{
         os << relation->getName() << " = ∅";
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamEmpty::relation private
Relation.
Definition at line 447 of file RamCondition.h.
Referenced by apply(), clone(), getChildNodes(), getRelation(), and print().
The documentation for this class was generated from the following file:
RamCondition.h