souffle: souffle::RamDrop Class Reference
souffle::RamDrop Class Reference
Drop relation, i.e., delete it from memory.
#include <RamStatement.h>
Public Member Functions
RamDrop * clone () const override
Create clone.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamDrop (std::unique_ptr< RamRelationReference > rel)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelationReference & getRelation () const
Get RAM relation.
RamRelationStatement (RamNodeType type, std::unique_ptr< RamRelationReference > r)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Additional Inherited Members
Protected Member Functions inherited from souffle::RamRelationStatement
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr
< RamRelationReference > relation
Relation.
Detailed Description
Drop relation, i.e., delete it from memory.
Definition at line 207 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamDrop::RamDrop (std::unique_ptr< RamRelationReference > rel) inline
Definition at line 209 of file RamStatement.h.
Referenced by clone().
 : RamRelationStatement(RN_Drop, std::move(rel)) {}
Member Function Documentation
RamDrop* souffle::RamDrop::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 217 of file RamStatement.h.
References RamDrop(), and souffle::RamRelationStatement::relation.
{
         RamDrop* res = new RamDrop(std::unique_ptr<RamRelationReference>(relation->clone()));
         return res;
     }
void souffle::RamDrop::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 212 of file RamStatement.h.
References souffle::RamRelationReference::getName(), and souffle::RamRelationStatement::getRelation().
{
         os << std::string(tabpos, '\t');
         os << "DROP " << getRelation().getName();
     }
The documentation for this class was generated from the following file:
RamStatement.h