souffle: souffle::RamPrintSize Class Reference
souffle::RamPrintSize Class Reference
Print relation size and a print message.
#include <RamStatement.h>
Public Member Functions
RamPrintSize * clone () const override
Create clone.
const std::string & getMessage () const
Get message.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamPrintSize (std::unique_ptr< RamRelationReference > rel)
Public Member Functions inherited from souffle::RamRelationStatement
void apply (const RamNodeMapper &map) override
Apply mapper.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelationReference & getRelation () const
Get RAM relation.
RamRelationStatement (RamNodeType type, std::unique_ptr< RamRelationReference > r)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::string message
print message
Protected Attributes inherited from souffle::RamRelationStatement
std::unique_ptr
< RamRelationReference > relation
Relation.
Detailed Description
Print relation size and a print message.
Print relation size for the printsize qualifier for relations.
Definition at line 994 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamPrintSize::RamPrintSize (std::unique_ptr< RamRelationReference > rel) inline
Definition at line 1000 of file RamStatement.h.
Referenced by clone().
             : RamRelationStatement(RN_PrintSize, std::move(rel)), message(relation->getName() + "\t") {}
Member Function Documentation
RamPrintSize* souffle::RamPrintSize::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 1016 of file RamStatement.h.
References RamPrintSize(), and souffle::RamRelationStatement::relation.
{
         RamPrintSize* res = new RamPrintSize(std::unique_ptr<RamRelationReference>(relation->clone()));
         return res;
     }
bool souffle::RamPrintSize::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamRelationStatement.
Definition at line 1023 of file RamStatement.h.
References souffle::RamRelationStatement::equal(), and message.
{
         assert(nullptr != dynamic_cast<const RamPrintSize*>(&node));
         const auto& other = static_cast<const RamPrintSize&>(node);
         RamRelationStatement::equal(other);
         return message == other.message;
     }
const std::string& souffle::RamPrintSize::getMessage () const inline
Get message.
Definition at line 1004 of file RamStatement.h.
References message.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalStmt().
{
         return message;
     }
void souffle::RamPrintSize::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 1009 of file RamStatement.h.
References souffle::RamRelationReference::getName(), souffle::RamRelationStatement::getRelation(), message, and souffle::stringify().
{
         os << std::string(tabpos, '\t');
         os << "PRINTSIZE " << getRelation().getName() << " TEXT ";
         os << "\"" << stringify(message) << "\"";
     }
Field Documentation
std::string souffle::RamPrintSize::message protected
print message
Definition at line 997 of file RamStatement.h.
Referenced by equal(), getMessage(), and print().
The documentation for this class was generated from the following file:
RamStatement.h