souffle: souffle::RamSwap Class Reference
souffle::RamSwap Class Reference
Swap operation two relations.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamSwap * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelationReference & getFirstRelation () const
Get first relation.
const RamRelationReference & getSecondRelation () const
Get second relation.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamSwap (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s)
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr
< RamRelationReference > first
first argument of swap statement
std::unique_ptr
< RamRelationReference > second
second argument of swap statement
Detailed Description
Swap operation two relations.
Definition at line 287 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamSwap::RamSwap (std::unique_ptr< RamRelationReference > f, std::unique_ptr< RamRelationReference > s) inline
Definition at line 296 of file RamStatement.h.
References first, and second.
Referenced by clone().
             : RamStatement(RN_Swap), first(std::move(f)), second(std::move(s)) {
         // TODO (#541): check not just for arity also for correct type!!
         assert(first->getArity() == second->getArity());
     }
Member Function Documentation
void souffle::RamSwap::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 331 of file RamStatement.h.
References first, map, and second.
{
         first = map(std::move(first));
         second = map(std::move(second));
     }
RamSwap* souffle::RamSwap::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 324 of file RamStatement.h.
References first, RamSwap(), and second.
{
         RamSwap* res = new RamSwap(std::unique_ptr<RamRelationReference>(first->clone()),
                 std::unique_ptr<RamRelationReference>(second->clone()));
         return res;
     }
bool souffle::RamSwap::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 338 of file RamStatement.h.
References getFirstRelation(), and getSecondRelation().
{
         assert(nullptr != dynamic_cast<const RamSwap*>(&node));
         const auto& other = static_cast<const RamSwap&>(node);
         return getFirstRelation() == other.getFirstRelation() &&
                getSecondRelation() == other.getSecondRelation();
     }
std::vector<const RamNode*> souffle::RamSwap::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 319 of file RamStatement.h.
References first, and second.
{
         return std::vector<const RamNode*>({first.get(), second.get()});  // no child nodes
     }
const RamRelationReference& souffle::RamSwap::getFirstRelation () const inline
Get first relation.
Definition at line 309 of file RamStatement.h.
References first.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalStmt().
{
         return *first;
     }
const RamRelationReference& souffle::RamSwap::getSecondRelation () const inline
Get second relation.
Definition at line 314 of file RamStatement.h.
References second.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalStmt().
{
         return *second;
     }
void souffle::RamSwap::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 303 of file RamStatement.h.
References first, and second.
{
         os << std::string(tabpos, '\t');
         os << "SWAP (" << first->getName() << ", " << second->getName() << ")";
     };
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamSwap::first protected
first argument of swap statement
Definition at line 290 of file RamStatement.h.
Referenced by apply(), clone(), getChildNodes(), getFirstRelation(), print(), and RamSwap().
std::unique_ptr<RamRelationReference> souffle::RamSwap::second protected
second argument of swap statement
Definition at line 293 of file RamStatement.h.
Referenced by apply(), clone(), getChildNodes(), getSecondRelation(), print(), and RamSwap().
The documentation for this class was generated from the following file:
RamStatement.h